- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
  tasks:
    - include: tasks/vscode.yml
    - include: tasks/mega.yml
    - include: tasks/gnome_extensions.yml
